### ISSUE TITLE
Bugs

### ISSUE THREAD

**Issue by winkler1** [daviferreira/react-viewport-slider#53]
Next button broken... http://screencast.com/t/h3x17zLx

**Comment by daviferreira** [comment]
Works fine for me, anything on the console? Cache maybe? :)

**Comment by daviferreira** [comment]
Nevermind, there was an issue with FF. Thanks again! :)

**Comment by winkler1** [comment]
Tried on another machine, and it looked OK. Both Chrome. Thanks, I'll check it out again tomorrow! :)
